apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-postgres
  template:
    metadata:
      labels:
        app: prod-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: proddb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: password
        volumeMounts:
        - name: prod-db-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: prod-db-persistent-storage
        persistentVolumeClaim:
          claimName: prod-db-pvc
