apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-dev
spec:
  replicas: 1
  container:
  - name: liquibase
    image: liquibase/liquibase:4.28.0
    command:
    - liquibase
    - update
    - --changelog=dev-db-changelog.xml
    - --change-set-context=dev
    - --url=jdbc:postgresql://db:5432/postgres
    - --username=postgres
    - --password=root
    volumeMounts:
    - name: liquibase-volume
      mountPath: /liquibase
  volumes:
  - name: liquibase-volume
    emptyDir: {}
