apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-prod
spec:
  replicas: 1
  container:
  - name: liquibase
    image: liquibase/liquibase:4.28.0
    command:
    - liquibase
    - update
    - --changelog=prod-db-changelog.xml
    - --change-set-context=prod
    - --url=jdbc:postgresql://db:5432/postgres
    - --username=postgres
    - --password=<your_prod_db_password>
    volumeMounts:
    - name: liquibase-volume
      mountPath: /liquibase
  volumes:
  - name: liquibase-volume
    emptyDir: {}
