apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: sara88/angular-app:5e8f1a82b373458eb801d84a8b57aac1fdde4c9f
          ports:
            - containerPort: 4200

---


apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: ClusterIP
