apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  hostNetwork: false
  port: 9080 
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.3.1
    helm:
      values: |
        server:
          service:
            type: LoadBalancer
            port: 9080 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  
